[window]
blur = true
decorations_theme_variant = "Dark"
dimensions = { columns = 120, lines = 30 }
opacity = 0.8
option_as_alt = "Both"

[font]
size = 14

[font.normal]
# family = "JetBrainsMono Nerd Font"
family = "Google Sans Code"
