theme = "focus_nova"
# theme = "base16_transparent"
# theme = "modus_operandi"

[editor]
line-number = "relative"
true-color = true
completion-replace = true
# rulers = [80, 100, 120]
color-modes = true
bufferline = "multiple"
end-of-line-diagnostics = "disable" # hint

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.statusline]
center = ["version-control"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-inlay-hints = true
snippets = true

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "underline"

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.whitespace.render]
space = "none"
tab = "none"
nbsp = "all"
nnbsp = "all"
newline = "none"

[keys.normal]
C-r = ":rl"
C-R = ":rla"
A-h = ":set file-picker.hidden false"
A-H = ":set file-picker.hidden true"
A-q = ":buffer-close"
A-Q = ":buffer-close!"
tab = ":buffer-next"
S-tab = ":buffer-previous"

[keys.insert.j]
j = "normal_mode"
k = "normal_mode"
